apiVersion: v1
kind: Service
metadata:
  name: eshop-auth-svc
  labels:
    app: eshop-auth-svc
spec:
  ports:
    - port: 8034
  selector:
    app: eshop-auth-deploy
    tier: frontend
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-auth-deploy
  labels:
    app: eshop-auth-deploy
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eshop-auth-deploy
        tier: frontend
    spec:
      containers:
      - image: eshop-auth-image:v1
        name: eshop-auth
        env:
        - name: DB_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: eshop-configmap
              key: eshop-auth-mysql-pass
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: eshop-configmap
              key: eshop-auth-mysql-host
        - name: DB_USER
          valueFrom:        
            configMapKeyRef:
              name: eshop-configmap
              key: eshop-auth-mysql-user
        ports:
        - containerPort: 8034
