apiVersion: v1
kind: Service
metadata:
  name: eshop-web-svc
  labels:
    app: eshop-web-svc
spec:
  ports:
    - port: 8033
      nodePort: 30080
  selector:
    app: eshop-web-deploy
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-web-deploy
  labels:
    app: eshop-web-deploy
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eshop-web-deploy
        tier: frontend
    spec:
      containers:
      - image: eshop-web:v1
        name: eshop
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app/eshop_service/config
        ports:
        -  containerPort: 8033
      volumes:
        - name: config-volume
          configMap:
            name: eshop-configmap
            items:
            - key: eshop-web-conf
              path: application.yml
