spring:
  application:
    name: eshop-cart-service
  redis:
    host: redis-svc
    port: 6379
    #password:
server:
  port: 8035
  context-path: /
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml
