apiVersion: v1
kind: Service
metadata:
  name: eshop-cart-svc
  labels:
    app: eshop-cart-svc
spec:
  ports:
    - port: 8035
  selector:
    app: eshop-cart-deploy
    tier: frontend
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-cart-deploy
  labels:
    app: eshop-cart-deploy
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eshop-cart-deploy
        tier: frontend
    spec:
      containers:
      - image: eshop-cart-image:v1
        name: eshop-cart
        ports:
        - containerPort: 8035
        volumeMounts:
          - name: config-volume
            mountPath: /opt/app/eshop_service/config
      volumes:
      - name: config-volume
        configMap:
          name: eshop-configmap
          items:
          - key: eshop-cart-conf
            path: application.yml
